### ISSUE TITLE
General UI polish checklist

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#404]
We need to do a polish of all of our work and make sure it conforms to Aragon App standards.

- [ ] Use the `IdentityBadge` component anywhere where Ethereum address are displayed
- [ ] Use [theme colors](https://ui.aragon.org/theme/) when available (as opposed to hard coded hex) 
- [ ] Ensure that we are using consistent styles for input fields (including color of placeholder text)
- [ ] Ensure that we are using consistent style for data validation / errors
- [ ] Ensure the required field asterisk is consistent
- [ ] Ensure we are using consistent icon colors 
- [ ] Ensure we are using consistent style for "information" boxes
- [ ] Use the standard code for etherscan base url
- [ ] Ensure we are including radspec text for smart contract functions triggered by the user that will require signing a transaction
- [ ] Test various parts of the UI for long text/truncation issues
- [ ] Test decimal truncation and use the Aragon App standard
- [ ] Ensure that the app works in mobile (major dapp browsers - Coinbase Wallet, Status, etc.)
- [ ] Ensure that the app works in Chrome, Safari, Firefox, Brave
